PizzeriaManagementApp/Models/Size.cs
using System;
using System.ComponentModel.DataAnnotations;

namespace PizzeriaManagementApp.Models
{
    public class Size
    {
        public Guid Id { get; set; }
        [Required]
        public string Name { get; set; }
        public int Value { get; set; }
    }
}

PizzeriaManagementApp/Controllers/SizeController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using PizzeriaManagementApp.Data;
using PizzeriaManagementApp.Models;
using System;
using System.Collections.Generic;

namespace PizzeriaManagementApp.Controllers
{
    [Authorize(Roles = "Admin, Manager")]
    public class SizeController : Controller
    {
        private readonly PizzeriaDbContext _dbContext;

        public SizeController(PizzeriaDbContext dbContext)
        {
            _dbContext = dbContext ?? throw new ArgumentNullException(nameof(dbContext));
        }

        public IActionResult Index()
        {
            IEnumerable<Size> sizes = _dbContext.Sizes;
            return View(sizes);
        }

        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Create(Size size)
        {
            if (ModelState.IsValid)
            {
                _dbContext.Sizes.Add(size);
                _dbContext.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(size);
        }

        public IActionResult Edit(Guid? id)
        {
            if (id == Guid.Empty || id is null)
            {
                return NotFound();
            }

            Size size = _dbContext.Sizes.Find(id);
            if (size is null)
            {
                return NotFound();
            }

            return View(size);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Edit(Size size)
        {
            if (ModelState.IsValid)
            {
                _dbContext.Sizes.Update(size);
                _dbContext.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(size);
        }

        public IActionResult Delete(Guid? id)
        {
            if (id == Guid.Empty || id is null)
            {
                return NotFound();
            }

            Size size = _dbContext.Sizes.Find(id);
            if (size is null)
            {
                return NotFound();
            }

            return View(size);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult DeleteConfirm(Guid? id)
        {
            Size size = _dbContext.Sizes.Find(id);
            if (size == null)
            {
                return NotFound();
            }

            _dbContext.Sizes.Remove(size);
            _dbContext.SaveChanges();
            return RedirectToAction("Index");
        }
    }
}

PizzeriaManagementApp/Views/Size/Create.cshtml
@model PizzeriaManagementApp.Models.Size

<form method="post" asp-action="Create">
    <div class="border p-3">
        <div class="form-group row">
            <h2 class="text-info p-3">Add size</h2>
        </div>
        <div class="row">
            <div class="col-8">
                <div class="form-group row">
                    <div class="col-4">
                        <label asp-for="Name"></label>
                    </div>
                    <div class="col-8">
                        <input asp-for="Name" class="form-control" />
                        <span asp-validation-for="Name" class="text-danger"></span>
                    </div>
                </div>
                <div class="form-group row">
                    <div class="col-4">
                        <label asp-for="Value"></label>
                    </div>
                    <div class="col-8">
                        <input asp-for="Value" class="form-control" />
                        <span asp-validation-for="Value" class="text-danger"></span>
                    </div>
                </div>
                <div class="form-group row">
                    <div class="col-8 offset-4 row">
                        <div class="col">
                            <input type="submit" class="btn btn-success w-100" value="Create" />
                        </div>
                        <div class="col">
                            <a asp-action="Index" class="btn btn-info w-100">
                                <i class="fas fa-sign-out-alt"></i> &nbsp; Back
                            </a>
                        </div>
                    </div>
                </div>
            </div>
            <div class="col-4">

            </div>
        </div>
    </div>
</form>

@section Scripts 
{
    @{ <partial name="_ValidationScriptsPartial" />}
}

PizzeriaManagementApp/Views/Size/Delete.cshtml
@model PizzeriaManagementApp.Models.Size

<form method="post" asp-action="DeleteConfirm">
    <input asp-for="Id" hidden />
    <div class="border p-3">
        <div class="form-group row">
            <h2 class="text-info p-3">Delete size</h2>
        </div>
        <div class="row">
            <div class="col-8">
                <div class="form-group row">
                    <div class="col-4">
                        <label asp-for="Name"></label>
                    </div>
                    <div class="col-8">
                        <input asp-for="Name" class="form-control" disabled />
                    </div>
                </div>
                <div class="form-group row">
                    <div class="col-4">
                        <label asp-for="Value"></label>
                    </div>
                    <div class="col-8">
                        <input asp-for="Value" class="form-control" disabled />
                    </div>
                </div>
                <div class="form-group row">
                    <div class="col-8 offset-4 row">
                        <div class="col">
                            <input type="submit" class="btn btn-danger w-100" value="Delete" />
                        </div>
                        <div class="col">
                            <a asp-action="Index" class="btn btn-info w-100">
                                <i class="fas fa-sign-out-alt"></i> &nbsp; Back
                            </a>
                        </div>
                    </div>
                </div>
            </div>
            <div class="col-4">

            </div>
        </div>
    </div>
</form>

@section Scripts
{
    @{
        <partial name="_ValidationScriptsPartial" />
    }
}

PizzeriaManagementApp/Views/Size/Edit.cshtml
@model PizzeriaManagementApp.Models.Size

<form method="post">
    <input asp-for="Id" hidden />
    <div class="border p-3">
        <div class="form-group row">
            <h2 class="text-info p-3">Edit size</h2>
        </div>
        <div class="row">
            <div class="col-8">
                <div class="form-group row">
                    <div class="col-4">
                        <label asp-for="Name"></label>
                    </div>
                    <div class="col-8">
                        <input asp-for="Name" class="form-control" />
                        <span asp-validation-for="Name" class="text-danger"></span>
                    </div>
                </div>
                <div class="form-group row">
                    <div class="col-4">
                        <label asp-for="Value"></label>
                    </div>
                    <div class="col-8">
                        <input asp-for="Value" class="form-control" />
                        <span asp-validation-for="Value" class="text-danger"></span>
                    </div>
                </div>
                <div class="form-group row">
                    <div class="col-8 offset-4 row">
                        <div class="col">
                            <input type="submit" class="btn btn-warning w-100" value="Update" />
                        </div>
                        <div class="col">
                            <a asp-action="Index" class="btn btn-info w-100">
                                <i class="fas fa-sign-out-alt"></i> &nbsp; Back
                            </a>
                        </div>
                    </div>
                </div>
            </div>
            <div class="col-4">

            </div>
        </div>
    </div>
</form>

@section Scripts
{
    @{
        <partial name="_ValidationScriptsPartial" />
    }
}

PizzeriaManagementApp/Views/Size/Index.cshtml
@model IEnumerable<PizzeriaManagementApp.Models.Size>

<div class="container p-3">
    <div class="row pt-4">
        <div class="col-6">
            <h2 class="text-primary">Size list</h2>
        </div>
        <div class="col-6 text-right">
            <a asp-controller="Size" asp-action="Create" class="btn btn-success">
                <i class="fas fa-plus"></i> &nbsp; Create new size
            </a>
        </div>
    </div>

    <br /><br />

    @if(Model.Count() > 0)
    {
        <table class="table table-bordered table-striped w-100">
            <thead>
                <tr>
                    <th>
                        Size name
                    </th>
                    <th>
                        Size value
                    </th>
                    <th>Actions</th>
                </tr>
            </thead>
            <tbody>
                @foreach(Size size in Model)
                {
                    <tr>
                        <td>
                            @size.Name
                        </td>
                        <td>
                            @size.Value
                        </td>
                        <td class="text-center">
                            <div class="w-75 btn-group" role="group">
                                <a asp-controller="Size" asp-action="Edit" asp-route-Id="@size.Id" class="btn btn-warning mx-2">
                                    <i class="fas fa-edit"></i>
                                </a>
                                <a asp-controller="Size" asp-action="Delete" asp-route-Id="@size.Id" class="btn btn-danger mx-2">
                                    <i class="fas fa-trash-alt"></i>
                                </a>
                            </div>
                        </td>
                    </tr>
                }
            </tbody>
        </table>
    }
    else
    {
        <p>No size exists.</p>
    }
</div>