PizzeriaManagementApp/Models/PizzaProducts.cs
using System;
using System.ComponentModel.DataAnnotations.Schema;

namespace PizzeriaManagementApp.Models
{
    public class PizzaProducts
    {
        public Guid Id { get; set; }
        public Guid IdPizza { get; set; }
        [ForeignKey("IdPizza")]
        public virtual Pizza Pizza { get; set; }

        public Guid IdProduct { get; set; }
        [ForeignKey("IdProduct")]
        public virtual Product Product { get; set; }
    }
}

PizzeriaManagementApp/ViewModels/PizzaProductsViewModel.cs
using System;
using System.Collections.Generic;

namespace PizzeriaManagementApp.ViewModels
{
    public class PizzaProductsViewModel
    {
        public Guid IdPizza { get; set; }
        public List<CheckBoxItem> ProductsCheckBoxList { get; set; }
    }
}

PizzeriaManagementApp/Controllers/PizzaProductsController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using PizzeriaManagementApp.Data;
using PizzeriaManagementApp.Models;
using PizzeriaManagementApp.ViewModels;
using System;
using System.Collections.Generic;
using System.Linq;

namespace PizzeriaManagementApp.Controllers
{
    [Authorize(Roles = "Admin, Manager")]
    public class PizzaProductsController : Controller
    {
        private readonly PizzeriaDbContext _dbContext;

        public PizzaProductsController(PizzeriaDbContext dbContext)
        {
            _dbContext = dbContext ?? throw new ArgumentNullException(nameof(dbContext));
        }

        public IActionResult Index(Guid id)
        {
            ICollection<PizzaProducts> pizzaProducts = _dbContext.PizzaProducts.Where(x => x.IdPizza == id).ToList();
            Pizza pizza = _dbContext.Pizzas.Where(x => x.Id == id).FirstOrDefault();
            foreach (PizzaProducts pizzaProduct in pizzaProducts)
            {
                pizzaProduct.Product = _dbContext.Products.FirstOrDefault(u => u.Id == pizzaProduct.IdProduct);
            }
            if (!pizzaProducts.Any())
            {
                pizzaProducts.Add(new PizzaProducts
                {
                    IdPizza = id
                });
            }
            PizzaProductsIndexVM pizzaProductVM = new()
            {
                PizzaName = pizza.Name,
                PizzaProducts = pizzaProducts
            };
            return View(pizzaProductVM);
        }

        public IActionResult Create(Guid id)
        {
            Guid[] existingProductsIds = _dbContext.PizzaProducts.Where(x => x.IdPizza == id).Select(x => x.IdProduct).ToArray();
            PizzaProductsVM pizzaProductsViewModel = new()
            {
                IdPizza = id,
                ProductsCheckBoxList = _dbContext.Products.Where(x => !existingProductsIds.Contains(x.Id)).Select(x => new CheckBoxItem<Guid>
                {
                    Id = x.Id,
                    Object = x,
                    IsChecked = false
                }).ToList()
            };
            return View(pizzaProductsViewModel);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Create(PizzaProductsVM pizzaProductsViewModel)
        {
            foreach (CheckBoxItem<Guid> pizzaProductCheckBox in pizzaProductsViewModel.ProductsCheckBoxList)
            {
                if (pizzaProductCheckBox.IsChecked)
                {
                    PizzaProducts pizzaProduct = new()
                    {
                        IdPizza = pizzaProductsViewModel.IdPizza,
                        IdProduct = pizzaProductCheckBox.Id
                    };
                    _dbContext.Add(pizzaProduct);
                    _dbContext.SaveChanges();
                }
            }
            return RedirectToAction("Index", new { id = pizzaProductsViewModel.IdPizza });
        }

        public IActionResult Delete(Guid id)
        {
            PizzaProducts pizzaProduct = _dbContext.PizzaProducts.Find(id);
            pizzaProduct.Pizza = _dbContext.Pizzas.Find(pizzaProduct.IdPizza);
            pizzaProduct.Product = _dbContext.Products.Find(pizzaProduct.IdProduct);
            if (pizzaProduct == null)
            {
                return NotFound();
            }
            return View(pizzaProduct);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult DeleteConfirm(Guid id)
        {
            PizzaProducts pizzaProduct = _dbContext.PizzaProducts.Find(id);
            if (pizzaProduct == null)
            {
                return NotFound();
            }
            _dbContext.Remove(pizzaProduct);
            _dbContext.SaveChanges();
            return RedirectToAction("Index", new { id = pizzaProduct.IdPizza });
        }
    }
}

PizzeriaManagementApp/Views/PizzaProducts/Create.cshtml
@model PizzeriaManagementApp.ViewModels.PizzaProductsVM

<form method="post" asp-action="Create">
    <input asp-for="IdPizza" hidden />
    <div class="border p-3">
        <div class="form-group row">
            <h2 class="text-info p-3">Add products to pizza</h2>
        </div>
        <div class="row">
            <div class="col-8 offset-2">
                @if (Model.ProductsCheckBoxList.Count > 0)
                {
                    <div class="form-group row">
                        <table class=" table table-bordered table-striped" style="width:100%">
                            <thead>
                                <tr>
                                    <th style="width:20%">
                                        Is selected
                                    </th>
                                    <th>
                                        Product name
                                    </th>
                                </tr>
                            </thead>
                            @for (int i = 0; i < Model.ProductsCheckBoxList.Count(); i++)
                            {
                                @Html.HiddenFor(p => p.ProductsCheckBoxList[i].Id)
                                <tr>
                                    <td>
                                        @Html.CheckBoxFor(p => p.ProductsCheckBoxList[i].IsChecked)
                                    </td>
                                    <td>
                                        @Html.DisplayFor(p => ((Product)p.ProductsCheckBoxList[i].Object).Name)
                                    </td>
                                </tr>
                            }
                        </table>
                    </div>
                }
                else
                {
                    <p class="text-center">All possible products are already assigned to this pizza</p>
                }
                <div class="form-group row">
                    <div class="col-8 offset-2 row">
                        @if (Model.ProductsCheckBoxList.Count > 0)
                        {
                            <div class="col">
                                <input type="submit" class="btn btn-info w-100" value="Add" />
                            </div>
                        }
                        <div class="col">
                            <a asp-controller="PizzaProducts" asp-route-Id="@Model.IdPizza" asp-action="Index" class="btn btn-primary w-100">Back</a>
                        </div>
                    </div>
                </div>
            </div>
            <div class="col-4">

            </div>
        </div>
    </div>
</form>

PizzeriaManagementApp/Views/PizzaProducts/Delete.cshtml
@model PizzeriaManagementApp.Models.PizzaProducts

<form method="post" asp-action="DeleteConfirm">
    <input asp-for="Id" hidden />
    <div class="border p-3">
        <div class="form-group row">
            <h2 class="text-info p-3">Delete product</h2>
        </div>
        <div class="row">
            <div class="col-8">
                <div class="form-group row">
                    <div class="col-4">
                        <label asp-for="Product.Name"></label>
                    </div>
                    <div class="col-8">
                        <input asp-for="Product.Name" class="form-control" disabled />
                    </div>
                </div>
                <div class="form-group row">
                    <div class="col-8 offset-4 row">
                        <div class="col">
                            <input type="submit" class="btn btn-danger w-100" value="Delete" />
                        </div>
                        <div class="col">
                            <a asp-action="Index" asp-route-Id="@Model.IdPizza" class="btn btn-info w-100">
                                <i class="fas fa-sign-out-alt"></i> &nbsp; Back
                            </a>
                        </div>
                    </div>
                </div>
            </div>
            <div class="col-4">

            </div>
        </div>
    </div>
</form>

@section Scripts
{
    @{
        <partial name="_ValidationScriptsPartial" />
    }
}

PizzeriaManagementApp/Views/PizzaProducts/Index.cshtml
@model PizzeriaManagementApp.ViewModels.PizzaProductsIndexVM

<div class="container p-3">
    <div class="row pt-4">
        <div class="col-6">
            <h2 class="text-primary">@Model.PizzaName products list</h2>
        </div>
        <div class="col-6 text-right">
            <a asp-route-Id="@Model.PizzaProducts.First().IdPizza" asp-controller="PizzaProducts" asp-action="Create" class=" btn btn-primary">
                <i class="fas fa-plus"></i>&nbsp; Add products
            </a>
            <a asp-controller="Pizza" asp-action="Index" class=" btn btn-info">
                <i class="fas fa-arrow-alt-circle-left"></i>&nbsp; Back
            </a>
        </div>
    </div>

    <br /><br />

    @if (Model.PizzaProducts.First().Id != Guid.Empty)
    {
        <table class="table table-bordered table-striped w-100">
            <thead>
                <tr>
                    <th>
                        Product name
                    </th>
                    <th>
                        Remove product from pizza
                    </th>
                </tr>
            </thead>
            <tbody>
                @foreach (PizzaProducts pizzaProduct in Model.PizzaProducts)
                {
                <tr>
                    <td>
                        @pizzaProduct.Product.Name
                    </td>
                    <td>
                        <a asp-route-Id="@pizzaProduct.Id" asp-controller="PizzaProducts" asp-action="Delete" class="btn btn-danger m-0 text-white">
                            <i class="fas fa-trash-alt"></i>
                        </a>
                    </td>
                </tr>
                }
            </tbody>
        </table>
    }
    else
    {
        <p>No pizza products are assigned.</p>
    }
</div>