PizzeriaManagementApp/Models/PizzeriaEmployee.cs
using System;
using System.ComponentModel.DataAnnotations.Schema;

namespace PizzeriaManagementApp.Models
{
    public class PizzeriaEmployee
    {
        public Guid Id { get; set; }
        public Guid PizzeriaId { get; set; }
        [ForeignKey("PizzeriaId")]
        public virtual Pizzeria Pizzeria { get; set; }

        public string EmployeeId { get; set; }
        [ForeignKey("EmployeeId")]
        public virtual Employee Employee { get; set; }
    }
}

PizzeriaManagementApp/Controllers/PizzeriaEmployeesController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using PizzeriaManagementApp.Data;
using PizzeriaManagementApp.Models;
using PizzeriaManagementApp.ViewModels;
using System;
using System.Collections.Generic;
using System.Linq;

namespace PizzeriaManagementApp.Controllers
{
    [Authorize(Roles = "Manager")]
    public class PizzeriaEmployeesController : Controller
    {
        private readonly PizzeriaDbContext _dbContext;
        private readonly UserManager<IdentityUser> _userManager;

        public PizzeriaEmployeesController(PizzeriaDbContext dbContext, UserManager<IdentityUser> userManager)
        {
            _dbContext = dbContext ?? throw new ArgumentNullException(nameof(dbContext));
            _userManager = userManager ?? throw new ArgumentNullException(nameof(userManager));
        }

        public IActionResult Index(Guid id)
        {
            ICollection<PizzeriaEmployee> pizzeriaEmployees = _dbContext.PizzeriaEmployees
                .Where(x => x.PizzeriaId == id)
                .ToList();
            Pizzeria pizzeria = _dbContext.Pizzerias
                .Where(x => x.Id == id)
                .FirstOrDefault();
            foreach (PizzeriaEmployee pizzeriaEmployee in pizzeriaEmployees)
            {
                pizzeriaEmployee.Employee = _dbContext.Employees
                    .FirstOrDefault(u => u.Id == pizzeriaEmployee.EmployeeId);
            }
            if (!pizzeriaEmployees.Any())
            {
                pizzeriaEmployees.Add(new PizzeriaEmployee
                {
                    PizzeriaId = id
                });
            }
            PizzeriaEmployeesIndexVM pizzeriaEmployeesVM = new()
            {
                PizzeriaName = pizzeria.Name,
                PizzeriaEmployees = pizzeriaEmployees
            };
            return View(pizzeriaEmployeesVM);
        }

        public IActionResult Create(Guid id)
        {
            string[] existingEmployeesIds = _dbContext.PizzeriaEmployees
                .Where(x => x.PizzeriaId == id)
                .Select(x => x.EmployeeId)
                .ToArray();
            PizzeriaEmployeesVM pizzeriaPizzasVM = new()
            {
                IdPizzeria = id,
                EmployeesCheckBoxList = _dbContext.Employees
                    .Where(x => !existingEmployeesIds.Contains(x.Id))
                    .Where(x => x.IdManager != null)
                    .Where(x => x.IdManager == _userManager.GetUserId(User))
                    .Select(x => new CheckBoxItem<string>
                {
                    Id = x.Id,
                    Object = x,
                    IsChecked = false
                }).ToList()
            };
            return View(pizzeriaPizzasVM);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Create(PizzeriaEmployeesVM pizzeriaEmployeesVM)
        {
            foreach (CheckBoxItem<string> pizzeriaEmployeeVM in pizzeriaEmployeesVM.EmployeesCheckBoxList)
            {
                if (pizzeriaEmployeeVM.IsChecked)
                {
                    PizzeriaEmployee pizzeriaEmployee = new()
                    {
                        PizzeriaId = pizzeriaEmployeesVM.IdPizzeria,
                        EmployeeId = pizzeriaEmployeeVM.Id
                    };
                    _dbContext.Add(pizzeriaEmployee);
                    _dbContext.SaveChanges();
                }
            }
            return RedirectToAction("Index", new { id = pizzeriaEmployeesVM.IdPizzeria });
        }

        public IActionResult Delete(Guid id)
        {
            PizzeriaEmployee pizzeriaEmployee = _dbContext.PizzeriaEmployees.Find(id);
            pizzeriaEmployee.Employee = _dbContext.Employees.Find(pizzeriaEmployee.EmployeeId);
            pizzeriaEmployee.Pizzeria = _dbContext.Pizzerias.Find(pizzeriaEmployee.PizzeriaId);
            if (pizzeriaEmployee == null)
            {
                return NotFound();
            }
            return View(pizzeriaEmployee);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult DeleteConfirm(Guid id)
        {
            PizzeriaEmployee pizzeriaEmployee = _dbContext.PizzeriaEmployees.Find(id);
            if (pizzeriaEmployee == null)
            {
                return NotFound();
            }
            _dbContext.Remove(pizzeriaEmployee);
            _dbContext.SaveChanges();
            return RedirectToAction("Index", new { id = pizzeriaEmployee.PizzeriaId });
        }
    }
}

PizzeriaManagementApp/Views/PizzeriaEmployees/Create.cshtml
@model PizzeriaManagementApp.ViewModels.PizzeriaEmployeesVM

<form method="post" asp-action="Create">
    <input asp-for="IdPizzeria" hidden />
    <div class="border p-3">
        <div class="form-group row">
            <h2 class="text-info p-3">Add employees to pizzeria</h2>
        </div>
        <div class="row">
            <div class="col-8 offset-2">
                @if (Model.EmployeesCheckBoxList.Count > 0)
                {
                    <div class="form-group row">
                        <table class=" table table-bordered table-striped" style="width:100%">
                            <thead>
                                <tr>
                                    <th style="width:20%">
                                        Is selected
                                    </th>
                                    <th>
                                        Employee name
                                    </th>
                                </tr>
                            </thead>
                            @for (int i = 0; i < Model.EmployeesCheckBoxList.Count(); i++)
                            {
                                @Html.HiddenFor(p => p.EmployeesCheckBoxList[i].Id)
                                <tr>
                                    <td>
                                        @Html.CheckBoxFor(p => p.EmployeesCheckBoxList[i].IsChecked)
                                    </td>
                                    <td>
                                        @Html.DisplayFor(p => ((Employee)p.EmployeesCheckBoxList[i].Object).FirstName) @Html.DisplayFor(p => ((Employee)p.EmployeesCheckBoxList[i].Object).LastName)
                                    </td>
                                </tr>
                            }
                        </table>
                    </div>
                }
                else
                {
                    <p class="text-center">All possible employees are already assigned to this pizzeria</p>
                }
                <div class="form-group row">
                    <div class="col-8 offset-2 row">
                        @if (Model.EmployeesCheckBoxList.Count > 0)
                        {
                            <div class="col">
                                <input type="submit" class="btn btn-success w-100" value="Add" />
                            </div>
                        }
                        <div class="col">
                            <a asp-controller="PizzeriaEmployees" asp-route-Id="@Model.IdPizzeria" asp-action="Index" class="btn btn-primary w-100">Back</a>
                        </div>
                    </div>
                </div>
            </div>
            <div class="col-4">

            </div>
        </div>
    </div>
</form>

PizzeriaManagementApp/Views/PizzeriaEmployees/Delete.cshtml
@model PizzeriaManagementApp.Models.PizzeriaEmployee

<form method="post" asp-action="DeleteConfirm">
    <input asp-for="Id" hidden />
    <div class="border p-3">
        <div class="form-group row">
            <h2 class="text-info p-3">Remove employee</h2>
        </div>
        <div class="row">
            <div class="col-8">
                <div class="form-group row">
                    <div class="col-4">
                        <label asp-for="Employee.FirstName"></label>
                    </div>
                    <div class="col-8">
                        <input asp-for="Employee.FirstName" class="form-control" disabled />
                    </div>
                </div>
                <div class="form-group row">
                    <div class="col-4">
                        <label asp-for="Employee.LastName"></label>
                    </div>
                    <div class="col-8">
                        <input asp-for="Employee.LastName" class="form-control" disabled />
                    </div>
                </div>
                <div class="form-group row">
                    <div class="col-8 offset-4 row">
                        <div class="col">
                            <input type="submit" class="btn btn-danger w-100" value="Remove" />
                        </div>
                        <div class="col">
                            <a asp-action="Index" asp-route-Id="@Model.PizzeriaId" class="btn btn-primary w-100">
                                <i class="fas fa-sign-out-alt"></i> &nbsp; Back
                            </a>
                        </div>
                    </div>
                </div>
            </div>
            <div class="col-4">

            </div>
        </div>
    </div>
</form>

@section Scripts
{
    @{
        <partial name="_ValidationScriptsPartial" />
    }
}

PizzeriaManagementApp/Views/PizzeriaEmployees/Index.cshtml
@model PizzeriaManagementApp.ViewModels.PizzeriaEmployeesIndexVM

<div class="container p-3">
    <div class="row pt-4">
        <div class="col-6">
            <h2 class="text-primary">@Model.PizzeriaName employees list</h2>
        </div>
        <div class="col-6 text-right">
            <a asp-route-Id="@Model.PizzeriaEmployees.First().PizzeriaId" asp-controller="PizzeriaEmployees" asp-action="Create" class="btn btn-success">
                <i class="fas fa-plus"></i>&nbsp; Add employees
            </a>
            <a asp-controller="Pizzeria" asp-action="Index" class="btn btn-primary">
                <i class="fas fa-arrow-alt-circle-left"></i>&nbsp; Back
            </a>
        </div>
    </div>

    <br /><br />

    @if (Model.PizzeriaEmployees.First().Id != Guid.Empty)
    {
        <table class="table table-bordered table-striped w-100">
            <thead>
                <tr>
                    <th>
                        Employee name
                    </th>
                    <th>
                        Remove employee from pizzeria
                    </th>
                </tr>
            </thead>
            <tbody>
                @foreach (PizzeriaEmployee pizzeriaEmployee in Model.PizzeriaEmployees)
                {
                <tr>
                    <td>
                        @($"{ pizzeriaEmployee.Employee.FirstName } { pizzeriaEmployee.Employee.LastName }")
                    </td>
                    <td>
                        <a asp-route-Id="@pizzeriaEmployee.Id" asp-controller="PizzeriaEmployees" asp-action="Delete" class="btn btn-danger m-0 text-white">
                            <i class="fas fa-trash-alt"></i>
                        </a>
                    </td>
                </tr>
                }
            </tbody>
        </table>
    }
    else
    {
        <p>No pizzeria employees are assigned.</p>
    }
</div>